### PR TITLE
Fix ambient .d.ts file import violations.

### PR DESCRIPTION
**Pull request by lelabo-m**
In issue #81, I explained that imports outside of the declare module scope violated the rules of ambient .d.ts files and the issues that comes with it.
In PR #85, I made some changes to the import order, but I forgot  that relative import where also forbidden.

In #87, @chungweileong94 suggested to change the import style.

This PR refactor `generateTypes.ts` once again to change the `_next-typesafe-url_.d.ts` generation with the following changes:
- Imports are all in the declare module scope.
- DynamicRouter interface generation as been simplified with a compatible import strategy (see below).

```ts
interface DynamicRouter {
   '/items/[id]': InferRoute<import('./src/app/items/[id]/routeType')>;
}
```

### CODE REVIEW

**Comment by chungweileong94** [comment]
Look about right to me👏

**Comment by ethanniser** [comment]
Will review tonight, but for now can you add a changeset?

Thanks for the contribution

**Comment by lelabo-m** [comment]
Sorry, but I am not sure what you mean?
The PR is already one commit and one commit if that what you mean...

**Comment by chungweileong94** [comment]
> I see something about changeset in the package, I will try to understand what it is...

Yes, this project is using changesets to manage the release + changelog. You can just run `npx changesets`, and follow the steps to add your change summary.

**Comment by ethanniser** [comment]
^^ yep thanks for explainaing
to clarify this would be a `patch` change
just run `pnpm changeset` write a description of the change and commit the file it generates

**Comment by lelabo-m** [comment]
I had a commit with the changeset with a thanks to @chungweileong94.

**Comment by ethanniser** [comment]
something came up will not be able to review tonight- hopefully tomorrow
thanks for understanding

**Comment by lelabo-m** [comment]
No problem. Happy to help. Take care.

**Comment by ethanniser** [comment]
looks great thanks so much

**Comment by ethanniser** [comment]
now live in 4.0.6!

**Pull request merged**
