### PR TITLE
fix: reset error state

### PR DESCRIPTION
**Pull request by izayl**
## This PR:

reset the error state for page useRouteParams hook.

step to reproduce issue:

1. visit a invalid route
2. write a hook with useEffect, which replace current invalid route to default route
3. isError will still true, error still exist

 - [x] Yes I have made a changeset

### CODE REVIEW

**Comment by ethanniser** [comment]
thanks

**Comment by izayl** [comment]
@ethanniser can help release a new version?

**Comment by izayl** [comment]
@izayl any updates?

**Comment by izayl** [comment]
@ethanniser any updates?

**Comment by ethanniser** [comment]
Sorry I'm super busy with school right now

Feel free to try and fix the action issue or patch your local version

**Comment by ethanniser** [comment]
btw I just tried to build this locally to publish it that way and i got the same errors in the actions so idek

**Comment by ethanniser** [comment]
fixed #111 
4.1.1 live now

**Pull request merged**
